matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      sudo: required

compiler:
  - gcc

script:
  - cd TBParser
  - chmod +x install-sh
  - ./install_deps.sh
  - ./configure && make && make install
