matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

language: cpp

compiler:
  - gcc

script:
  - cd TBParser
  - chmod +x install-sh
  - ./install_deps.sh
  - ./configure && make && make install
