matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python:
        - "2.7"
      install:
        - pip install -r requirements.txt
      script:
        - echo "n" | ./install.sh
        - python -m pytest
    - os: osx
      install:
        - pip2 install -r requirements.txt
      script:
        - echo "n" | ./install.sh
        - python2 -m pytest
