matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - cmake
            - gcc
    - os: osx
      sudo: required
      before_install:
        - brew install cmake

language: cpp

compiler:
  - gcc

script:
  - cd TBParser
  - chmod +x install-sh
  - ./install_deps.sh
  - ./configure && make && make install
